Sprint 3
ClevertecFrontendLab/demos461 pull request #3
Opened 2024-03-03 21:03 UTC by demos461

2024-03-03 21:05 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709499942/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709499942/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709499942/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709499942/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709499942/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709499942/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709499942/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709499942/updated-review-list.png)

2024-03-04 08:20 UTC, dariavorom requested changes
![image](https://github.com/ClevertecFrontendLab/demos461/assets/64946271/9b52b1a3-2889-4d4b-be34-31d8ae29ef13)
не хватает плейсхолдера в текстовом поле

2024-03-04 08:20 UTC, dariavorom commented on src/components/AppHeader/appHeader.module.scss
> +        padding: 0 24px 16px 24px;
много повторяющихся размеров отступов: тоже повыносить в переменные

2024-03-04 10:00 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709546451/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709546451/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709546451/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709546451/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709546451/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709546451/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709546451/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709546451/updated-review-list.png)

2024-03-04 10:07 UTC, dariavorom approved these changes

2024-03-04 10:07 UTC, dariavorom commented on src/pages/MainPage/mainPage.module.scss
> +    padding: var(--padding-24);
все хорошо, только можно переименовать, не завязываясь цифрами) потому что, если изменится дизайн (например, базовые отступы с 16px увеличились до 18px), то смысл теряется. обычно именуют наподобие: --gap-s, --gap-xs или --indent-m. это рекомендация просто

2024-03-04 14:48 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709563733/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709563733/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709563733/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709563733/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709563733/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709563733/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709563733/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709563733/updated-review-list.png)

2024-03-04 19:24 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709580264/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709580264/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709580264/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709580264/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709580264/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709580264/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709580264/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1709580264/updated-review-list.png)

2024-03-05 08:13 UTC, dariavorom approved these changes

2024-03-05 15:55 UTC, merged