feat: implement training page
ClevertecFrontendLab/demos461 pull request #6
Opened 2024-04-10 11:56 UTC by demos461

2024-04-10 12:10 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**come-to-trainings-1_1440x900 (1).png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/come-to-trainings-1_1440x900%20(1).png)
***
**come-to-trainings-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/come-to-trainings-1_1440x900.png)
***
**create-joint-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/create-joint-training-1_1440x900.png)
***
**create-joint-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/create-joint-training-2_1440x900.png)
***
**create-joint-training-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/create-joint-training-3_360x740.png)
***
**create-joint-training-4_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/create-joint-training-4_360x740.png)
***
**create-new-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/create-new-training-1_833x900.png)
***
**create-new-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/create-new-training-2_833x900.png)
***
**take-joint-training-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/take-joint-training-1_833x900.png)
***
**take-joint-training-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/take-joint-training-2_833x900.png)
***
**take-joint-training-3_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/take-joint-training-3_833x900.png)
***
**take-joint-training-4_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/take-joint-training-4_833x900.png)
***
**update-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/update-trainings-1_360x740.png)
***
**update-trainings-2_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/update-trainings-2_360x740.png)
***
**update-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/demos461/1712751038/update-trainings-3_360x740.png)

2024-04-10 15:22 UTC, Ivan6813 requested changes

2024-04-10 15:22 UTC, Ivan6813 commented on src/components/Training/JointTraining/JointTrainingDrawer/jointTrainingDrawer.module.scss
> +            gap: var(--gap-xs);
под margin, padding и gap можно завести общие переменные, которые отвечают за отступы
это как совет

2024-04-10 15:22 UTC, Ivan6813 commented on src/components/Training/JointTraining/TrainingPartners/TrainingPartners.tsx
> +            {trainingPartners.length ? (
под такие проверки было бы неплохо написать утилитку isArrayWithItems, это функция, которая будет проверять переданный массив на наличие в нем элементов и возвращать булево. Думаю мест, где идет проверка на пустоту хватает, по проекту

2024-04-10 15:22 UTC, Ivan6813 commented on src/components/Training/JointTraining/TrainingPartners/TrainingPartners.tsx
> +                        trainingPartners.length > 4 && {
4 - magic number, такое нужно выносить в константы и давать им понятное название, это улучшит читаемость кода

2024-04-10 17:58 UTC, Ivan6813 approved these changes

2024-04-10 21:05 UTC, ValadzkoAliaksei requested changes

2024-04-10 21:05 UTC, ValadzkoAliaksei commented on src/api/api.ts
> +    JointTrainingsStatus,
![image](https://github.com/ClevertecFrontendLab/demos461/assets/61273546/3afb215c-d11e-4a01-abd3-c69c3519ba66)
поиск не работает

2024-04-10 21:05 UTC, ValadzkoAliaksei commented on src/api/api.ts
> +    getUserJointTrainingList(trainingType?: string, status?: JointTrainingsStatus) {
![image](https://github.com/ClevertecFrontendLab/demos461/assets/61273546/94e68ca4-9e22-42de-875c-2641cf9a9f0a)
модалка висит уже пол часа

2024-04-10 21:05 UTC, ValadzkoAliaksei commented on src/api/api.ts
> +        return instance.get<JointTrainingListResponseType[]>(ApiUrl.USER_JOINT_TRAINING_LIST, {
![image](https://github.com/ClevertecFrontendLab/demos461/assets/61273546/9612b1be-db47-46a4-9b9b-1ec257b294bd)
кнопка не работает(

2024-04-11 09:40 UTC, demos461 commented on src/api/api.ts
> +    JointTrainingsStatus,
Так работает же, на enter или при нажатии лупы, проверил и локально и на gh-pages

2024-04-11 11:11 UTC, ValadzkoAliaksei approved these changes

2024-04-11 11:16 UTC, merged